/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

/**
 * @nullable
 */
export type _EventsVersionVersionStatus =
  | (typeof _EventsVersionVersionStatus)[keyof typeof _EventsVersionVersionStatus]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _EventsVersionVersionStatus = {
  draft: 'draft',
  published: 'published',
} as const;
