/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */
import type { AccessCollectionsFieldsCreate } from './accessCollectionsFieldsCreate';
import type { AccessCollectionsFieldsRead } from './accessCollectionsFieldsRead';
import type { AccessCollectionsFieldsUpdate } from './accessCollectionsFieldsUpdate';

export type AccessCollectionsFields = {
  [key: string]: {
    create: AccessCollectionsFieldsCreate;
    read: AccessCollectionsFieldsRead;
    update: AccessCollectionsFieldsUpdate;
  };
};
