/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export type CommunitiesCommunityLocationItem = {
  /** @nullable */
  address?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  formattedAddress?: string | null;
  /** @nullable */
  googleMapsUrl?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  mapImageUrl?: string | null;
  /** @nullable */
  placeId?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  zip?: string | null;
};
