/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export type CommunitiesPhotosItem = {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  url?: string | null;
};
