/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */
import type { _CommunitiesVersionVersionStatus } from './_communitiesVersionVersionStatus';
import type { CommunitiesVersionVersionCommunityMembersItem } from './communitiesVersionVersionCommunityMembersItem';
import type { CommunitiesVersionVersionCommunityOrganizersItem } from './communitiesVersionVersionCommunityOrganizersItem';
import type { CommunitiesVersionVersionCreatedBy } from './communitiesVersionVersionCreatedBy';
import type { CommunitiesVersionVersionParentCommunity } from './communitiesVersionVersionParentCommunity';
import type { CommunitiesVersionVersionSubcommunitiesItem } from './communitiesVersionVersionSubcommunitiesItem';

export type CommunitiesVersionVersion = {
  /** @nullable */
  _status?: _CommunitiesVersionVersionStatus;
  /** @nullable */
  communityLongDescription?: string | null;
  /** @nullable */
  communityMembers?: CommunitiesVersionVersionCommunityMembersItem[] | null;
  communityName: string;
  /** @nullable */
  communityOrganizers?: CommunitiesVersionVersionCommunityOrganizersItem[] | null;
  communitySummary: string;
  createdBy?: CommunitiesVersionVersionCreatedBy;
  parentCommunity?: CommunitiesVersionVersionParentCommunity;
  slug: string;
  /** @nullable */
  subcommunities?: CommunitiesVersionVersionSubcommunitiesItem[] | null;
};
