/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export interface ImageUploads {
  createdAt: string;
  /** @nullable */
  filename?: string | null;
  /** @nullable */
  filesize?: number | null;
  /** @nullable */
  focalX?: number | null;
  /** @nullable */
  focalY?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  mimeType?: string | null;
  updatedAt: string;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  width?: number | null;
}
