/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export type PatchImageUploadsIdParams = {
  /**
   * number of levels to automatically populate relationships and uploads
   */
  depth?: number;
  /**
   * retrieves document(s) in a specific locale
   */
  locale?: string;
  /**
   * specifies a fallback locale if no locale value exists
   */
  'fallback-locale'?: string;
};
