/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export type PayloadPreferencesUserOneOfRelationTo =
  (typeof PayloadPreferencesUserOneOfRelationTo)[keyof typeof PayloadPreferencesUserOneOfRelationTo];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayloadPreferencesUserOneOfRelationTo = {
  users: 'users',
} as const;
