/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */
import type { PayloadPreferencesValueAnyOf } from './payloadPreferencesValueAnyOf';

/**
 * @nullable
 */
export type PayloadPreferencesValue =
  | PayloadPreferencesValueAnyOf
  | unknown[]
  | string
  | number
  | boolean
  | null;
