/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */
import type { PayloadPreferencesUserOneOf } from './payloadPreferencesUserOneOf';
import type { PayloadPreferencesValue } from './payloadPreferencesValue';

export interface PayloadPreferences {
  createdAt: string;
  /** @nullable */
  key?: string | null;
  updatedAt: string;
  user: PayloadPreferencesUserOneOf;
  /** @nullable */
  value?: PayloadPreferencesValue;
}
