/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */
import type { UsersRolesItem } from './usersRolesItem';

export interface Users {
  createdAt: string;
  email: string;
  /** @nullable */
  hash?: string | null;
  /** @nullable */
  lockUntil?: string | null;
  /** @nullable */
  loginAttempts?: number | null;
  /** @nullable */
  password: string | null;
  /** @nullable */
  resetPasswordExpiration?: string | null;
  /** @nullable */
  resetPasswordToken?: string | null;
  roles: UsersRolesItem[];
  /** @nullable */
  salt?: string | null;
  updatedAt: string;
}
