/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */
import type { Users } from './users';

export interface UsersMe {
  exp?: number;
  token?: string;
  /** @nullable */
  user: Users;
}
