/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export type UsersRolesItem = (typeof UsersRolesItem)[keyof typeof UsersRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersRolesItem = {
  superAdmin: 'superAdmin',
  systemAdmin: 'systemAdmin',
  communityOrganizer: 'communityOrganizer',
  coach: 'coach',
  sponsor: 'sponsor',
  member: 'member',
} as const;
