/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * payload
 * A blank template to get started with Payload
 * OpenAPI spec version: 0.0.1
 */

export interface Where {
  and?: Where[];
  or?: Where[];
  [key: string]:
    | WhereAnyOf
    | WhereAnyOfTwo
    | WhereAnyOfThree
    | WhereAnyOfFive
    | WhereAnyOfSeven
    | WhereAnyOfNine
    | WhereAnyOfOneone
    | WhereAnyOfOnetwo
    | WhereAnyOfOnethree
    | WhereAnyOfOnefour
    | WhereAnyOfOnefive
    | WhereAnyOfOnesix;
}
